-- Create a table for public profiles (Existing)
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text check (role in ('student', 'teacher', 'admin')),
  school_id text,
  grade_level text,
  strand text,
  avatar_url text,
  status text default 'Active' check (status in ('Active', 'Pending', 'Suspended', 'Inactive')),
  last_active timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);


-- TRANSACTIONS TABLE
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text check (type in ('income', 'expense')) not null,
  category text not null,
  amount numeric(12, 2) not null,
  description text,
  date date not null default CURRENT_DATE,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table transactions enable row level security;

create policy "Users can view their own transactions" on transactions for select using (auth.uid() = user_id);
create policy "Users can insert their own transactions" on transactions for insert with check (auth.uid() = user_id);
create policy "Users can update their own transactions" on transactions for update using (auth.uid() = user_id);
create policy "Users can delete their own transactions" on transactions for delete using (auth.uid() = user_id);


-- SAVINGS GOALS TABLE
create table if not exists savings_goals (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  target_amount numeric(12, 2) not null,
  current_amount numeric(12, 2) not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table savings_goals enable row level security;

create policy "Users can view their own savings goals" on savings_goals for select using (auth.uid() = user_id);
create policy "Users can insert their own savings goals" on savings_goals for insert with check (auth.uid() = user_id);
create policy "Users can update their own savings goals" on savings_goals for update using (auth.uid() = user_id);
create policy "Users can delete their own savings goals" on savings_goals for delete using (auth.uid() = user_id);


-- BADGES TABLE (System-wide definitions)
create table if not exists badges (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  icon text not null, -- Store lucide icon name or image URL
  color text, -- tailwind color class
  bg_color text, -- tailwind bg class
  criteria jsonb, -- e.g. {"transactions_count": 10}
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table badges enable row level security;

create policy "Badges are viewable by everyone" on badges for select using (true);
-- Only admins should be able to insert/update/delete badges (handled by app logic or further policies)


-- USER BADGES TABLE (Many-to-Many)
create table if not exists user_badges (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  badge_id bigint references badges not null,
  earned_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, badge_id)
);

alter table user_badges enable row level security;

create policy "Users can view their own earned badges" on user_badges for select using (auth.uid() = user_id);
-- Insert policy might depend on backend logic (system awards badges)
create policy "System can insert user badges" on user_badges for insert with check (true); 


-- Insert some default badges
insert into badges (name, description, icon, color, bg_color) values
('Budget Beginner', 'Create your first budget transaction', 'Award', 'text-blue-500', 'bg-blue-100'),
('Savings Star', 'Reach 10% of your savings goal', 'Star', 'text-yellow-500', 'bg-yellow-100'),
('Quiz Whiz', 'Score 100% on 3 quizzes', 'Trophy', 'text-purple-500', 'bg-purple-100'),
('Entrepreneur', 'Submit your first business idea', 'Medal', 'text-emerald-500', 'bg-emerald-100'),
('Consistent Learner', 'Log in for 7 days in a row', 'Award', 'text-orange-500', 'bg-orange-100'),
('Forum Friend', 'Reply to 5 discussion topics', 'Star', 'text-pink-500', 'bg-pink-100')
on conflict do nothing;
